Parse jason
AngelaLee18/MVC pull request #1
Opened 2022-08-24 17:31 UTC by AngelaLee18

MVC

Parse Json and activity indicator

DESCRIPTION

In this branch i parse the json file on background and add the activity indicator.

EVIDENCE

<img width="364" alt="Screen Shot 2022-08-24 at 14 29 57" src="https://user-images.githubusercontent.com/109097550/186484951-b5e3d9e2-7286-4d4a-a71c-b8fc8bb88eee.png">

<img width="563" alt="Screen Shot 2022-08-24 at 14 30 52" src="https://user-images.githubusercontent.com/109097550/186485118-fd06016b-07f7-4115-a208-3679c50d1bfd.png">

2022-08-24 20:10 UTC, ezequielvelezglobant requested changes
Also there is no test for the parser. Please add it.

2022-08-24 20:10 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Controller/ViewController.swift
> +        }*/
there should not be commented code

2022-08-24 20:10 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Model/Parse.swift
> +            }
do not use if let, instead use guard statement

2022-08-24 20:10 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Controller/ViewController.swift
> +        }
the idea of the indicator is show that the data is being parse. There is missing the call to get the TedTalks from Parser.

2022-08-24 21:14 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Controller/ViewController.swift
> +        }*/
Corrected

2022-08-24 21:14 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Model/Parse.swift
> +            }
Ok, solved

2022-08-25 18:18 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Model/Parse.swift
> +            }
6bc402faf519621cdfbd6c1bde73ffc85e4e9449

2022-08-25 18:22 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Controller/ViewController.swift
> +        }
Solved it d7b327bd79c00255aaabf48855a39e1a40b8f5b6

2022-08-25 18:51 UTC, ezequielvelezglobant requested changes

2022-08-25 18:51 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Controller/ViewController.swift
> +        }
the stop of the indicator was to be when we get the result of getDataTedTalks

2022-08-25 18:51 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Model/DataManager.swift
> +        Parse().parseTedTalk("tedTalks") { result in DispatchQueue.main.async {
add a line break before DispatchQueue

2022-08-26 18:13 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Model/DataManager.swift
> +        Parse().parseTedTalk("tedTalks") { result in DispatchQueue.main.async {
5201db083d82893e742c4f8a3a86f718b3e78d71

2022-08-26 18:13 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Controller/ViewController.swift
> +        }
5201db083d82893e742c4f8a3a86f718b3e78d71

2022-08-26 20:14 UTC, ezequielvelezglobant approved these changes

2022-08-29 14:23 UTC, JMVarelaGlobant approved these changes

2022-08-29 14:31 UTC, merged