Search bar
AngelaLee18/MVC pull request #3
Opened 2022-09-01 14:17 UTC by AngelaLee18

MVC

SearchBar and pickerView

DESCRIPTION

In this branch I created the searchBar and pickerView to perform searches according to the selected picker and what was entered in the search bar. And in the play list is only showed the result about the according to all the filter. 

EVIDENCE

https://user-images.githubusercontent.com/109097550/187936604-f2920427-4d3b-49a1-95c4-c370d6dfbf45.mov

2022-09-01 14:46 UTC, ezequielvelezglobant requested changes
The PR should point to Module_2/main branch!

2022-09-01 14:46 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/View/SearchBarCellModel.swift
> +}
For what is that class?

2022-09-01 14:46 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Controller/ViewController.swift
> +
do not add extra lines.

2022-09-01 14:46 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Controller/ViewController.swift
> +        return result
you don't need this result array. Just return manager.searchEnteredWord(...

2022-09-01 14:46 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Model/DataManager.swift
> +    func getDataTedTalks(completionHandler: @escaping ([TedTalkData]) -> Void) {
Add space between properties and func, y also recomend to use marks: https://cocoacasts.com/organize-your-swift-project-with-annotations-todos-and-fixmes

2022-09-01 14:46 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Model/DataManager.swift
> +                return talk.event.lowercased().contains(searchText.lowercased())
this is wrong, the default case should be "All"

2022-09-01 15:16 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/View/SearchBarCellModel.swift
> +}
e291d24a351e3b4f108b2f0c998ea0711b95c960

2022-09-01 15:16 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Controller/ViewController.swift
> +
8bf510de592cf4a3430bad7daa807e3305c18cfb

2022-09-01 15:16 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Controller/ViewController.swift
> +        return result
fd09155f3d4178703777a575543d0ca86c279d3f

2022-09-01 15:16 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Model/DataManager.swift
> +                return talk.event.lowercased().contains(searchText.lowercased())
b5c3a9ba7a86befc08ae71810a70f705f706bc3a

2022-09-01 15:16 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Model/DataManager.swift
> +    func getDataTedTalks(completionHandler: @escaping ([TedTalkData]) -> Void) {
b5c3a9ba7a86befc08ae71810a70f705f706bc3a

2022-09-01 15:17 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Model/DataManager.swift
> +                return talk.event.lowercased().contains(searchText.lowercased())
54b6ddb6f18c698e7ce79d9b875c384d7e74cc02

2022-09-01 19:04 UTC, ezequielvelezglobant commented
@AngelaLee18 Please review the UI, there is an extra table that is not needed. And the table should start right before the pickerView.
![image](https://user-images.githubusercontent.com/84336500/187992678-73b7a338-83d2-4e30-a94b-5e97f882f566.png)

2022-09-05 14:44 UTC, ezequielvelezglobant approved these changes

2022-09-05 16:22 UTC, JMVarelaGlobant approved these changes

2022-09-05 16:47 UTC, merged