Detail view
AngelaLee18/MVC pull request #4
Opened 2022-09-05 14:13 UTC by AngelaLee18

MVC

View Controller to show details

DESCRIPTION

In this branch I created a navigation controller to show some details of a talk that the user chooses. 

EVIDENCE

https://user-images.githubusercontent.com/109097550/188468695-966948ba-68a4-4cfc-a76c-58dd3a1ce9ed.mov

2022-09-05 16:55 UTC, ezequielvelezglobant requested changes
![image](https://user-images.githubusercontent.com/84336500/188492056-e98f6b60-0ac1-49d7-8abd-9ad9a22aef70.png)
Review the UI, some labels like title or tags are not multi-line, and in small screen the text is cropped.

2022-09-05 16:55 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Controller/DetailViewController.swift
> +    @IBOutlet weak var webView: WKWebView!
please order this, first the outlets then the properties

2022-09-05 17:24 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Controller/DetailViewController.swift
> +    @IBOutlet weak var webView: WKWebView!
48d9fe8ed59aa13e64b1b26354a68ddcaecc183e

2022-09-07 12:06 UTC, ezequielvelezglobant requested changes
Review de UI, the searchbar is not working. you have constraints problems

2022-09-07 12:06 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Controller/DetailViewController.swift
> +        let myRequest = URLRequest(url: myURL!)
do not use force unwrap!

2022-09-07 16:14 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Controller/DetailViewController.swift
> +        let myRequest = URLRequest(url: myURL!)
fef5bfbb6d3af8b4fda3b5698bda622a3187f4e2

2022-09-07 16:14 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Controller/DetailViewController.swift
> +        let myRequest = URLRequest(url: myURL!)
Corrected 
fef5bfbb6d3af8b4fda3b5698bda622a3187f4e2

2022-09-08 12:55 UTC, ezequielvelezglobant approved these changes

2022-09-12 14:04 UTC, JMVarelaGlobant approved these changes

2022-09-12 14:08 UTC, merged