fetch json with NSURLSession
AngelaLee18/MVC pull request #5
Opened 2022-09-05 19:33 UTC by AngelaLee18

MVC

NSURLSession

DESCRIPTION

In this branch I fetched json with NSURLSession.

EVIDENCE 

https://user-images.githubusercontent.com/109097550/188505568-599cc025-9efe-4379-82f4-d029bedac065.mov

2022-09-06 12:28 UTC, JMVarelaGlobant requested changes

2022-09-06 12:28 UTC, JMVarelaGlobant commented on Ted Talk/Ted Talk/Model/Parse.swift
>          DispatchQueue.global(qos: .background).async {
You don't need it more, URLSession create a new thread to execute the task

2022-09-06 12:28 UTC, JMVarelaGlobant commented on Ted Talk/Ted Talk/Model/Parse.swift
> +            let url = URL(string: "https://gist.githubusercontent.com/gonzaloperretti/0e79c229a5de5bacdd07f402c1a3cefd/raw/975582a4389601caa90d21227446ef2838159176/tedTalks.json")
Please create a constant for the URL string

2022-09-06 12:28 UTC, JMVarelaGlobant commented on Ted Talk/Ted Talk/Model/Parse.swift
> +            session.dataTask(with: url!) { data, response, error in
Please don't use ! symbol, the app can crash, instead you need to unwrap this with guard or if statement

2022-09-06 12:28 UTC, JMVarelaGlobant commented on Ted Talk/Ted Talk/Model/Parse.swift
> +                    let dataFromJson = try jsonDecoder.decode([TedTalkData].self, from: data!)
Same here with data, please don't use ! symbol

2022-09-06 14:00 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Model/Parse.swift
>          DispatchQueue.global(qos: .background).async {
6891856e1e790de79b3e6b27a23ddbce804db071

2022-09-06 14:00 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Model/Parse.swift
> +            let url = URL(string: "https://gist.githubusercontent.com/gonzaloperretti/0e79c229a5de5bacdd07f402c1a3cefd/raw/975582a4389601caa90d21227446ef2838159176/tedTalks.json")
6891856e1e790de79b3e6b27a23ddbce804db071

2022-09-06 14:00 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Model/Parse.swift
> +            session.dataTask(with: url!) { data, response, error in
6891856e1e790de79b3e6b27a23ddbce804db071

2022-09-06 14:00 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Model/Parse.swift
> +                    let dataFromJson = try jsonDecoder.decode([TedTalkData].self, from: data!)
6891856e1e790de79b3e6b27a23ddbce804db071

2022-09-06 14:25 UTC, JMVarelaGlobant requested changes

2022-09-06 14:25 UTC, JMVarelaGlobant commented on Ted Talk/Ted Talk/Model/Parse.swift
> +            return
You should add completion(.failure(.badURL)) here

2022-09-06 14:25 UTC, JMVarelaGlobant commented on Ted Talk/Ted Talk/Model/Parse.swift
> +        session.dataTask(with: url) { data, response, error in guard let data = data else {
Please add a line break here after **_in_**, the guard statement should be placed in the next line

2022-09-06 14:25 UTC, JMVarelaGlobant commented on Ted Talk/Ted Talk/Model/Parse.swift
> +                completion(.failure(.serverError))
This guard should be placed at the begining, together with the others "checks for error", and later if all is ok, try to decode data

2022-09-06 15:39 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Model/Parse.swift
> +                completion(.failure(.serverError))
447fda10546dfbb2471b68883006ede04207aa6f

2022-09-06 15:39 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Model/Parse.swift
> +        session.dataTask(with: url) { data, response, error in guard let data = data else {
Solved it

2022-09-07 12:13 UTC, ezequielvelezglobant requested changes

2022-09-07 12:13 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Model/Parse.swift
> +        let urlAsString = "https://gist.githubusercontent.com/gonzaloperretti/0e79c229a5de5bacdd07f402c1a3cefd/raw/975582a4389601caa90d21227446ef2838159176/tedTalks.json"
Move this url to a enum of constants

2022-09-07 12:13 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Model/Parse.swift
>              }
fix alignment

2022-09-07 12:13 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Model/Parse.swift
>              }
NotFound is not a descriptive name. This case should be empty data

2022-09-07 12:13 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Model/Parse.swift
>      func parseTedTalk(_ tedTalks: String, _ completion: @escaping (Result<[TedTalkData], ParseError>) -> Void ) {
This is not a Parser class and a parseFunction, instead of modified the old parser create a new class service provider or something like this.
Also I recommend to create a service protocol and the Parser and ServiceProvider can implemented, then is easy to change from DataManager what to use.

2022-09-07 18:58 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Model/Parse.swift
>      func parseTedTalk(_ tedTalks: String, _ completion: @escaping (Result<[TedTalkData], ParseError>) -> Void ) {
c4c085d20c07fcb210565a9db65df09a3eeb2170

2022-09-07 18:58 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Model/Parse.swift
>              }
Corrected 
c4c085d20c07fcb210565a9db65df09a3eeb2170

2022-09-07 18:58 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Model/Parse.swift
> +        let urlAsString = "https://gist.githubusercontent.com/gonzaloperretti/0e79c229a5de5bacdd07f402c1a3cefd/raw/975582a4389601caa90d21227446ef2838159176/tedTalks.json"
Solved c4c085d20c07fcb210565a9db65df09a3eeb2170

2022-09-12 12:57 UTC, ezequielvelezglobant approved these changes

2022-09-12 14:04 UTC, JMVarelaGlobant approved these changes

2022-09-12 14:09 UTC, merged