Mvvm
AngelaLee18/MVC pull request #6
Opened 2022-09-09 17:36 UTC by AngelaLee18

MVC

MVVM

DESCRIPTION

In this branch I refactored from mvc pattern to mvvm pattern

EVIDENCE

<img width="298" alt="Screen Shot 2022-09-09 at 14 35 46" src="https://user-images.githubusercontent.com/109097550/189411143-1e91cd91-04c5-46f1-a645-35aded6cb3dd.png">

2022-09-12 13:03 UTC, ezequielvelezglobant requested changes

2022-09-12 13:03 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/View/DetailCellModel.swift
> +        url = talk.url
why this?

2022-09-12 13:03 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/Model/DataManager.swift
> +            case 5:
Move this function to ViewModel, never use numbers in case. If I read this I don't know which represent that number.

2022-09-12 15:26 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/Model/DataManager.swift
> +            case 5:
08d2e56303c7a013de5b73255a8721debbaac8e8

2022-09-12 15:26 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/View/DetailCellModel.swift
> +        url = talk.url
Deleted the space 
08d2e56303c7a013de5b73255a8721debbaac8e8

2022-09-12 16:37 UTC, JMVarelaGlobant approved these changes

2022-09-13 14:15 UTC, ezequielvelezglobant requested changes

2022-09-13 14:15 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/View/TableViewController.swift
> +        }
You have to add [weak self] to avoid Retain Cycle!

2022-09-13 17:02 UTC, ezequielvelezglobant requested changes

2022-09-13 17:02 UTC, ezequielvelezglobant commented on Ted Talk/Ted TalkTests/SearchBarAndPickerViewTest.swift
>      }
fix test

2022-09-14 17:47 UTC, AngelaLee18 commented on Ted Talk/Ted TalkTests/SearchBarAndPickerViewTest.swift
>      }
a996ad8dd0377685329af0c5371350c904141a43

2022-09-14 17:47 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/View/TableViewController.swift
> +        }
Added it
a996ad8dd0377685329af0c5371350c904141a43

2022-09-15 12:54 UTC, ezequielvelezglobant approved these changes

2022-09-15 13:58 UTC, JMVarelaGlobant approved these changes

2022-09-15 13:58 UTC, merged