Lottie
AngelaLee18/MVC pull request #8
Opened 2022-09-14 13:41 UTC by AngelaLee18

LOTTIE

DESCRIPTION

In this branch I added Lottie and using a loader animation instead of activity indicator.

EVIDENCE

https://user-images.githubusercontent.com/109097550/190170218-87b3dec3-a12f-4db5-9cb9-0f1875bfbca9.mov

2022-09-14 13:49 UTC, ezequielvelezglobant requested changes
Remember to fix the MVVM comments and merge those changes into this branch.

2022-09-14 13:49 UTC, ezequielvelezglobant commented on Ted Talk/Podfile
> +pod 'lottie-ios'
move to line 9. In this way you will know that is for all Ted Talk target

2022-09-14 18:57 UTC, RafaBenaGlobant commented on Ted Talk/Ted TalkTests/SearchBarAndPickerViewTest.swift
> +        searchResult = sut.searchByFilter(searchText: "event", picker: "Event")
Now ViewModelTedTalk, not DataManager, is responsible for 'searchByFilter' but the test is not reflecting it.

2022-09-14 21:53 UTC, AngelaLee18 commented on Ted Talk/Podfile
> +pod 'lottie-ios'
fc1099a7604956dc603a1208cc4d948ae3893834

2022-09-14 21:54 UTC, AngelaLee18 commented on Ted Talk/Ted TalkTests/SearchBarAndPickerViewTest.swift
> +        searchResult = sut.searchByFilter(searchText: "event", picker: "Event")
Correted 
2f3b00a8f4ca04701f3758f9597315166cd17c32

2022-09-15 14:08 UTC, ezequielvelezglobant requested changes

2022-09-15 14:08 UTC, ezequielvelezglobant commented on Ted Talk/Podfile
> +	pod 'lottie-ios'
remove extra tabulation.

2022-09-15 14:08 UTC, ezequielvelezglobant commented on Ted Talk/Ted Talk/View/TableViewController.swift
> +            DispatchQueue.main.asyncAfter(deadline: .now() + 2.0) {
there is an extra space and also a missing weak self

2022-09-15 14:17 UTC, AngelaLee18 commented on Ted Talk/Podfile
> +	pod 'lottie-ios'
a94ce78491b4e27284abacb47269c863317f5059

2022-09-15 14:17 UTC, AngelaLee18 commented on Ted Talk/Ted Talk/View/TableViewController.swift
> +            DispatchQueue.main.asyncAfter(deadline: .now() + 2.0) {
a94ce78491b4e27284abacb47269c863317f5059

2022-09-15 18:16 UTC, ezequielvelezglobant approved these changes

2022-09-15 19:03 UTC, RafaBenaGlobant approved these changes

2022-09-16 12:33 UTC, JMVarelaGlobant approved these changes

2022-09-16 12:34 UTC, merged